name: Roots API CI

on:
  push:
    branches: [ "feature-workflow" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DB_DATABASE: roots_test_db
      DB_USER: root
      DB_PASSWORD: root
      APP_ENV: test
      DATABASE_URL : mysql://${{ DB_USER }}:${{ DB_PASSWORD }}@127.0.0.1:3306/${{ DB_DATABASE }}
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: install npm 
        run: |
          npm install
      - name: run tests
        run: |
          npx prisma generate
          npx prisma migrate deploy
          npm run test
          npm run jest --config ./test/jest-e2e.json
